server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters: # cors설정 : 헤더 중복 에러 해결
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/auth/**,/api/user-service/oauth2/**,/api/user-service/docs/**,/api/user-service/actuator/**
          filters:
            - AuthFilter
            - RewritePath=/api/user-service/(?<segment>.*), /${segment}

        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - AuthPermissionFilter
            - RewritePath=/api/user-service/(?<segment>.*), /${segment}

        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/store-service/**
          filters:
            - AuthFilter
            - RewritePath=/api/store-service/(?<segment>.*), /${segment}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-service/**
          filters:
            - AuthPermissionFilter
            - RewritePath=/api/order-service/(?<segment>.*), /${segment}

        - id: payment-service-public
          uri: lb://payment-service
          predicates:
            - Path=/api/payment-service/webhook/**,/api/payment-service/docs/**
          filters:
            - AuthFilter
            - RewritePath=/api/payment-service/(?<segment>.*), /${segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment-service/**
          filters:
            - AuthPermissionFilter
            - RewritePath=/api/payment-service/(?<segment>.*), /${segment}


        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai-service/**
          filters:
            - AuthPermissionFilter
            - RewritePath=/api/ai-service/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
