services:
  postgres-cart:
    image: postgres:latest
    container_name: cart-postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=${LOCAL_DB}
      - POSTGRES_USER=${LOCAL_DB_USERNAME}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}