spring:
  application:
    name: ${SERVICE_NAME:ai-service}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_service}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
    minimum-idle: ${HIKARI_MIN_IDLE:5}

server:
  port: ${SERVER_PORT:8087}

weather:
  api:
    key: ${WEATHER_API_KEY:}
    url: https://api.openweathermap.org/data/2.5/weather

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

user:
  service:
    url: http://localhost:8081

logging:
  level:
    root: ${LOG_LEVEL:INFO}