server:
  port: 8015

spring:
  application:
    name: ai-service

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    eureka:
      instance:
        prefer-ip-address: true
      client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    driver-class-name: org.postgresql.Driver
    #    driver-class-name: org.h2.Driver # 테스트용
    username: root
    password: 1234
  cloud:
    config:
      enabled: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

weather:
  api:
    key: 4fb89bac013fcdc53f48552cca7bee9a
    url: https://api.openweathermap.org/data/2.5/weather

gemini:
  api:
    key: AIzaSyCB7kf7oiqe0xf0cA9jzuZy26i_VBUqN3Y
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent


logging:
  level:
    root: ${LOG_LEVEL:INFO}

