server:
  port: 8014

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  cloud:
    config:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      url: ${REDIS_URL}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-secret: ${JWT_REFRESH_SECRET}
  refresh-expiration: 604800000