services:
  postgres:
    image: postgres:latest
    container_name: sample-postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=${LOCAL_DB}
      - POSTGRES_USER=${LOCAL_DB_USERNAME}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}

  redis:
    image: redis:latest
    container_name: sample-redis
    ports:
      - 6379:6379