collector.receiver.grpc.agent.enable=true
collector.receiver.grpc.agent.bindaddress.ip=0.0.0.0
collector.receiver.grpc.agent.bindaddress.port=9991

collector.receiver.grpc.stat.enable=true
collector.receiver.grpc.stat.bindaddress.ip=0.0.0.0
collector.receiver.grpc.stat.bindaddress.port=9992

collector.receiver.grpc.span.enable=true
collector.receiver.grpc.span.bindaddress.ip=0.0.0.0
collector.receiver.grpc.span.bindaddress.port=9993
