server:
  port: 8013

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoOperations: DEBUG

spring:
  application:
    name: store-service
  profiles:
    active: local
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  data:
    mongodb:
      uri: mongodb+srv://jh010303:1234@deliverycluster.lnwvpzp.mongodb.net/sample_mflix
  datasource:
    url: jdbc:postgresql://localhost:5435/store_db
    driver-class-name: org.postgresql.Driver
    #    driver-class-name: org.h2.Driver # 테스트용
    username: user
    password: password
  cloud:
    config:
      enabled: false